# Generated by Django 5.1.5 on 2025-02-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('video', models.CharField(max_length=100, verbose_name='Ссылка на видео')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
