# Generated by Django 5.1.5 on 2025-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='file',
            field=models.CharField(default='', max_length=1000, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='fio',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='video',
            field=models.CharField(default='', max_length=1000, verbose_name='Ссылка на видео'),
        ),
    ]
