# Generated by Django 5.1.5 on 2025-02-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clients_file_alter_clients_fio_alter_clients_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='file',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='video',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('src', models.CharField(default='', max_length=1000, verbose_name='Ссылка на файл')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('src', models.CharField(default='', max_length=1000, verbose_name='Ссылка на видео')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
        ),
    ]
