# Generated by Django 5.1.5 on 2025-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_links_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(default='', max_length=3000, verbose_name='Полное описание')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(default='', max_length=3000, verbose_name='Новость')),
            ],
        ),
        migrations.AddField(
            model_name='promotions',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
